# Generated by Django 4.2.1 on 2023-05-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2500)),
                ('uid', models.CharField(max_length=500)),
                ('dateTime', models.DateTimeField()),
                ('channelName', models.CharField(max_length=500)),
            ],
        ),
    ]
