# Generated by Django 4.2.1 on 2023-05-16 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chat_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chat',
            table='Chat',
        ),
    ]
